name: Zeitsteuerung

on:
  schedule:
    - cron: "*/30 * * * *"   # Alle 30 Minuten (UTC)
  workflow_dispatch:         # Manuell starten möglich

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawler starten
        run: python crawl.py
