name: Zeitsteuerung

on:
  schedule:
    - cron: "*/240 * * * *"   # Alle 240 Minuten (UTC)
  workflow_dispatch:         # manuell auslösbar über GitHub Actions

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Installiere Playwright + Browser
        run: |
          playwright install

      - name: Crawler starten
        run: python crawler/crawl.py   # ✅ Pfad zum Skript
