name: Zeitsteuerung

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4 pydantic python-dotenv playwright

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Create data directory
        run: mkdir -p data

      - name: Run crawler
        run: python crawler/crawl.py
        env:
          # Falls du OUTPUT_CSV in der .env überschreiben willst:
          # OUTPUT_CSV: data/results.csv
          PYTHONUNBUFFERED: 1
