name: Zeitsteuerung

on:
  schedule:
    - cron: "0 */4 * * *"   # Jede 4. Stunde um :00 Uhr UTC
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Erhöhtes Timeout für komplexe Crawls

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4 pydantic python-dotenv playwright

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium  # Stellt alle Abhängigkeiten sicher

      - name: Create data directory
        run: mkdir -p crawler/data

      - name: Run crawler
        working-directory: ./crawler
        run: python -u crawl.py  # -u für ungepufferte Ausgabe
        env:
          OUTPUT_CSV: data/results.csv
          # Füge hier weitere benötigte Umgebungsvariablen hinzu
          PYTHONUNBUFFERED: 1  # Sofortige Log-Ausgabe
